### ISSUE TITLE
Unable to run Protocol test Manager using CLI

### ISSUE THREAD

**Issue by skalra23** [Microsoft/WindowsProtocolTestSuites#104]
We were looking at the Protocol Test Manager tool to run protocol compliance test suits MS-SMB2 specifically against our systems. I was able to run them successfully using GUI, but I wanted to know how can I run using CLI. I searched on web to find more about it and found the  presentation on 'Enhanced User Experience' from Vivian Tian from plugfest 2016. It seems like ptmcli.exe is the command to do that. But when I run this command with the profile file it seems unable to parse the file correctly.  I have generated profile file using the “Save Profile” option from the GUI. However it seems the profile file it is generating cannot be used directly /corrupted. I wanted to know if there is a solution by which I can generate clean profile file.  
I tried to clean up the profile file manually by opening it in text editor but it seems like I might have deleted some extra data/or couldn’t find all the corrupted data.   
Following are the few errors I get when I load the profile file:
“There is an error in XML document (0,0)”
After cleaning most of the control characters in the file I get “File contains corrupted data”

I am attaching a generated corrupted profile file for you to have a look at it. 
Please let me know how else I can generate this file and run a subset of test cases using cli.

**Comment by JiajunW** [comment]
I am using the profile saved from PTM GUI, and it appears ptmcli can use the profile to run cases. FYI, the comand I am using is:

`PtmCli.exe -p test.ptm -r test.txt -s -outcome pass,fail,inconclusive,notrun`

And yes, the profile itself is not a clean XML, do not need to clean it.

To better diagnose the problem, it will be helpful if you provide more information on it:
- The command you use. The output of PtmCli.
- You can attach the profile saved using GUI, so that I can check if I can use the profile to repro the issue.

**Comment by skalra23** [comment]
Hello, I am unable to upload .ptm files here. I even tried to uplaod the .zip, i am unable to to do that. If you can provide me an email, i can attach it ?
Following is the error message i am getting:
PS C:\Program Files (x86)\Protocol Test Manager\bin> .\PtmCli.exe -p C:\Users\sunny\Desktop\frontline\winProfile.ptm -r test.txt
ERROR:
There is an error in XML document (0, 0).

Thank you

**Comment by JiajunW** [comment]
I can upload a zip file to here. Not quite sure why it failed..

And It seems that GitHub filter files by filename extension. As a workaround, you can rename the ptm file to one of png/gif/jpg/txt, and try to upload it.

**Comment by skalra23** [comment]
![winprofile](https://cloud.githubusercontent.com/assets/149489/24127942/c2004fc6-0d95-11e7-8213-ec6315c41112.jpg)

Hello I have uploaded a sample profile file that is failing.
Please change the file extension to .ptm.

**Comment by JiajunW** [comment]
Can you provide the version info of:
- Test suite
- Protocol Test Framework
- Protocol Test Manager

And, can you load the profile using the PTM GUI?

**Comment by skalra23** [comment]
Following are the versions i am using:
Protocol Test Framework v1.0.2485.0
Protocol Test Manager v1.0.2508.0

Test Suite is Microsoft FileSharing_TestSuite_ServerEP v1.0.2508.0
I am specifically running MS-SMB2 test cases. 
Thank you

**Comment by skalra23** [comment]
I tried to load the profile using GUI and i get same errors as i was getting using CLI.

**Comment by JiajunW** [comment]
It seems that you are using a quite old version of test suite. The bug is fixed in the latest code.

### Option 1

You could try our latest release:
- PTF from https://github.com/Microsoft/ProtocolTestFramework/releases (you should use ProtocolTestFrameworkInstallerForModel.msi)
- FileServer-TestSuite-ServerEP.msi from https://github.com/Microsoft/WindowsProtocolTestSuites/releases
- ProtocolTestManager.msi from https://github.com/Microsoft/WindowsProtocolTestSuites/releases

And you also need to install Spec Explorer (https://visualstudiogallery.msdn.microsoft.com/271d0904-f178-4ce9-956b-d9bfa4902745/) since FileServer contains some model-based test cases.

### Option 2

You can build PTF, PTM, FileServer test suite yourself using the latest code on GitHub.

**Note:** You need to add `-outcome pass,fail,inconclusive,notrun` in the command as arguments. It seems the `outcome` argument has no default value (which is different from what the ppt says.. I will fix it later)

**Comment by skalra23** [comment]
I downloaded the latest release and it runs smoothly. That's awesome! It will help in automating these test cases. Thank you!

**Comment by JiajunW** [comment]
I think the reason is there is spaces in the argument. There should be no spaces in `pass,fail,inconclusive,notrun`. Or quotes is required like `"pass, fail"` so that the program can receive the argument.

**Comment by yazeng** [comment]
Close it since no update for a long time.
