### ISSUE TITLE
Warnings seen during build of ProtocolTestFramework

### ISSUE THREAD

**Issue by akilanmaris** [Microsoft/WindowsProtocolTestSuites#105]
I tried building the ProtocolTestFramework on a 64 bit Windows 7 machine after installing all the prerequisites. I'm getting some 130 warnings as mentioned below.

C:\Windows\Microsoft.NET\Framework\v4.0.30319\Microsoft.Common.targets(1578,5): warning MSB3270: There was a mismatch
 between the processor architecture of the project being built "MSIL" and the processor architecture of the reference "
C:\Windows\Microsoft.NET\Framework\v4.0.30319\mscorlib.dll", "x86". This mismatch may cause runtime failures.

However, when I tried building the same on a 32 bit Windows 8.1 machine, I got similar 149 warnings related to x64 architecture. Is it fine to ignore these warnings ?

After building the ProtocolTestFramework, I tried to build the MS-SMB TestSuite. Similar warnings were seen there as well. But at the end it was mentioned that it is built successfully. I also got the .msi file as mentioned in the readme.

Now I referred to the user guide(https://github.com/Microsoft/WindowsProtocolTestSuites/blob/staging/TestSuites/MS-SMB/docs/MS-SMB_ServerUserGuide.md) of MS-SMB TestSuite. After reading the user guide, I have the following doubts.

- Is this test suite suitable to run on SUTs with only NTFS or FAT file systems ?
- Should I assign the IPs of SUT, driver computer and DC exactly as mentioned in the user guide ?
- Is it mandatory to have an isolated network ?
- should the driver computer definitelyt be 32 bit Windows 8.1 ?
- After running ./ConfigServer or /.ConfigClient, is there any way to reconfigure them ? (If I do it now, it says the script is already run)

**Comment by yazeng** [comment]
Thank you for contacting us.
It's fine to ignore the build warnings. 
For your doubts:
1. The test suite is designed for NTFS and FAT. But most of the cases the file system type is just used to verify some endnotes of the protocol. I suggest you run all the test cases and see where the failure is.
2. No, you do not need to assign the ip exactly the same as user guide. But if you change the SUT name or share folder name, remember to update the file below accordingly:
WindowsProtocolTestSuites\TestSuites\MS-SMB\src\TestSuite\MS-SMB_ServerTestSuite.deployment.ptfconfig
3. We recommend isolated network because of security, since the password is clear text saved in the above config file.
4. No, 64-bit is also OK. Actually, we use 64-bit in our lab for regression test.
5. If you want to rerun the scripts, remove the file "config.finished.signal" under "c:\".
Hope that helps.

Thanks,
Yan
