### ISSUE TITLE
MS-SMB : Can you share an example MS-SMB_ServerTestSuite.deployment.ptfconfig file for SMB implementations for Linux?

### ISSUE THREAD

**Issue by tymok** [Microsoft/WindowsProtocolTestSuites#130]
Hello.

Can you share an example MS-SMB_ServerTestSuite.deployment.ptfconfig file for SMB implementations for Linux such as samba?

Actually I am trying to run MS-SMB testsuite with a Linux-kernel-embedded SMB implementation and have some configuration issues.
I configure my test environment after reading MS-SMB_ServerUserGuide.md, but still have problems.
If you provide Linux SUT configuration detail, It will be really helpful.

By the way, Please check attatched test result and let me know if you found anything strange.
[USER_CLIENT01 2017-12-23 14_29_17.zip](https://github.com/Microsoft/WindowsProtocolTestSuites/files/1583940/USER_CLIENT01.2017-12-23.14_29_17.zip)

Best Regards,
Taeyang Mok

**Comment by chenlu0616** [comment]
Hi, Taeyang

Sorry to say that currently we don’t have the SMB ptfconfig file for Linux environment. Normally we just run against windows environment for SMB and the config file is as the same as you download from github.
After checked the trx file you attached, the connection cannot be setup between driver and SUT thus the TCs threw socket exception. It’s probably caused by "SutMachineName" or "SutPort" configuration wrong. 
 
You have to make sure that you can ping the “SutMachineName” successfully, and the SMB service running on your SUT is listening on port 445(for windows). Here are some suggestions:
1.	Make sure the firewall service is turned off on your SUT.
2.	Make sure SMB service is listening on the 445 port(e.g.), if not, modify the config file.
3.	Make sure you can use windows file explorer via SMB(you may need to manually enable SMB, depending on the windows OS you use) to open the file share on your SUT.

Hopefully it will help!

Thanks,
Lu

**Comment by tymok** [comment]
Hi Lu,

Thanks for the advise.
As you pointed out, SutMachineName setting is the cause of the problem.

Best Regards,
Taeyang Mok
