### ISSUE TITLE
[MS-SMB] System.InvalidOperationException: unexpected end of channel stream: expected 1 more byte

### ISSUE THREAD

**Issue by tymok** [Microsoft/WindowsProtocolTestSuites#132]
Hello.

I got some error messages while running MS-SMB testsuites.
With the test result, I found that many exceptions "System.InvalidOperationException: unexpected end of channel stream: expected 1 more byte(s)" occured with my SMB server implementation.
Could you check and inform why the error occured and what it means?
[USER_DRIVER 2017-12-26 14_35_53.zip](https://github.com/Microsoft/WindowsProtocolTestSuites/files/1586800/USER_DRIVER.2017-12-26.14_35_53.zip)

Best Regards,
Taeyang Mok

**Comment by chenlu0616** [comment]
Hi, Taeyang

I looked into the errors and it seems that the exception is thrown because the test suite SDK failed to decode SMB Negotiate response packet returned by your SMB server, and the response should contain one more byte as the SDK expects while reading the stream, thus the assertion here failed.

Since I cannot debug to get more information, here I have the windows network capture for "TraditionalTestCase_Disconnect_14_Case

", which run pass on the windows test environment, you can take it as a reference to see the message differences
[TraditionalTestCase_Disconnect_14_Case.matp.zip](https://github.com/Microsoft/WindowsProtocolTestSuites/files/1588684/TraditionalTestCase_Disconnect_14_Case.matp.zip)
. Capture with Microsoft Message Analyzer which you can download from website.

Thanks,
Lu

**Comment by yazeng** [comment]
Close this issue since no response for a long time.
