### ISSUE TITLE
Two similar documents about SUT Remote Control Protocol in a source repository

### ISSUE THREAD

**Issue by ligurio** [microsoft/WindowsProtocolTestSuites#168]
I have found two similar documents in a source repository:
- [TestSuites/RDP/RDPSUTControlAgent/Docs/SUT_Remote_Control_Protocol.pdf](https://github.com/microsoft/WindowsProtocolTestSuites/blob/staging/TestSuites/RDP/RDPSUTControlAgent/Docs/SUT_Remote_Control_Protocol.pdf)
- [TestSuites/RDP/Client/docs/SUT_Remote_Control_Protocol.pdf](https://github.com/microsoft/WindowsProtocolTestSuites/blob/staging/TestSuites/RDP/Client/docs/SUT_Remote_Control_Protocol.pdf)

Both documents have same release date (August 19, 2015), but first one has change according to revision summary on a second page with comment "Add missing information".

Could you provide more details about change?

**Comment by huiren-jiang** [comment]
Hi Sergey,

Thanks for your feedback, and sorry for any confusion caused by these duplicate documents. We will fix this issue soon in our next release.

Please refer to the document with version **0.2**. The comment "Add missing information" mainly refers to adding the missing **caseNameLength** and **caseName** fields in **SUT Control Request Message**. Also, this change includes several improvements to the description of fields and processing.

Best Regards,

Windows Protocol Test Suites Development Team

**Comment by ligurio** [comment]
Huiren, thanks for an answer!
Tracking changes of documentation in binary formats is difficult when storing in an VCS. Is it possible to convert PDF and DOC files to text formats like Markdown, AsciiDoc or anything else? it would be much more convenient.

**Comment by huiren-jiang** [comment]
Hi Sergey,

Thanks for your feedback. Your suggestion sounds good and we will consider to do this in our next release. 

Best Regards,

Windows Protocol Test Suites Development Team

**Comment by sweeetday** [comment]
Hi, Sergey
 We have updated the docs according to your suggestions. You can get the latest md files commit https://github.com/microsoft/WindowsProtocolTestSuites/commit/3fe7a886b8d12ab0fd7d2a6d8c2f25b784ddaa8c 
 Thanks for your feedback.

**Comment by ligurio** [comment]
Thanks a lot! (correct commit id is 93248be76e521c9e7e2af427f42527d3e23b35d0)
