### ISSUE TITLE
create a communication forum for WPTS questions

### ISSUE THREAD

**Issue by jtmoon79** [microsoft/WindowsProtocolTestSuites#188]
I'm trying to setup the Windows Protocol Test Suites on a Windows Server.  I have many questions that are not answered by the documentation.  I do not want to create a github issue for every question.

Could the Windows Protocol Test Suites team create an additional communications forum?  Something like a Slack channel, or an email list, or an IRC chat, or a web forum, or a [Jekyll Disqus Forum](https://github.com/klcodanr/Jekyll-Disqus-Forum#jekyll-disqus-forum)?  Any one of these would help tremendously.

**Comment by lumengyanhelen** [comment]
Hi James,

We currently don't have a forum or other channels due to the maintenance effort. We will see if we can build that later. For now, you may append new questions you have to one fixed GitHub issue if that can work better or email us. We will go through them and get back to you asap.

Thanks,
Helen
