### ISSUE TITLE
Need clarification with test case Smb2Multichannel_2Channels_DiffTransport

### ISSUE THREAD

**Issue by vinitagnihotri** [microsoft/WindowsProtocolTestSuites#205]
I am trying to run mentioned test case and test case fails with error code
STATUS_USER_SESSION_DELETED

In packet captures over RDMA and TCP I could see client guid in negotiate requests are different,  so as per SMB2 specs (3.3.5.5) 
If Session.Connection.ClientGuid is not the same as Connection.ClientGuid, the
server MAY fail the request with STATUS_USER_SESSION_DELETED.
seems correct response. So why does test case fails?

Please take a look at attached capture files.
![smbd-multichannel-capture_rdma](https://user-images.githubusercontent.com/54569394/64856169-04017980-d63f-11e9-9f36-57937aace699.png)
![smbd-multichannel-capture_tcp](https://user-images.githubusercontent.com/54569394/64856171-049a1000-d63f-11e9-8fb1-b9d3b7885879.png)

**Comment by huiren-jiang** [comment]
Hi vinitagnihotri,

The term MAY indicates Windows implementation does not follow the prescription, while it's up to third parity's decision to choose whether to follow or not.

To make the test cases as interoperable as possible, we think it is more sensible to make the clientGuid consistent among different sessions in multiple channel scenario. We will fix this later so that the test case will not fail before the actual testing. Thanks for reporting this issue!

Best Regards,

Windows Protocol Test Suites Development Team

**Comment by vinitagnihotri** [comment]
Thanks.

**Comment by huiren-jiang** [comment]
Hi vinitagnihotri,

This issue should be fixed by commit 37e1400. Thanks for your contribution.

Best Regards,

Windows Protocol Test Suites Development Team

**Comment by vinitagnihotri** [comment]
Is this fixed in version 3.19.9.0 as we still see this issue with 3.19.9.0

**Comment by huiren-jiang** [comment]
Hi vinitagnihotri,

This fix is not in the release of 3.19.9.0 since it is committed after the release.

The solution is:

1.	You could build the SMBD installer from staging by yourself, if you have your own develop environment.

1.	Or we can build one for you with the latest code. 

Best Regards,

Windows Protocol Test Suites Development Team

**Comment by vinitagnihotri** [comment]
Unfortunately I don't have development environment for the same, 
it would be great help if we can go ahead with option 2 with latest commit, so that we would be able to validate other outstanding issues as well.

Thanks, really appreciate your help.

**Comment by huiren-jiang** [comment]
Hi vinitagnihotri,

Here I attach a signed build with fix [MS-SMBD-TestSuite-ServerEP.msi.zip](https://github.com/microsoft/WindowsProtocolTestSuites/files/3903425/MS-SMBD-TestSuite-ServerEP.msi.zip). You could uninstall the old, then try this one to verify the fix. 

Best Regards,

Windows Protocol Test Suites Development Team

**Comment by lumengyanhelen** [comment]
Hi vinitagnihotri,

Since this thread has been inactive for a long time, we close it for now. Feel free to reopen it if the problem remains.

Windows Protocol Test Suites Development Team
