### ISSUE TITLE
Issue with SMBD test cases  Smb2OverRdma_Read/Write_SMB2_CHANNEL_RDMA_V1

### ISSUE THREAD

**Issue by vinitagnihotri** [microsoft/WindowsProtocolTestSuites#211]
We are running SMBD server equivalent in centos enviroment. While running this 
Smb2OverRdma_Read_SMB2_CHANNEL_RDMA_V1 and
Smb2OverRdma_Write_SMB2_CHANNEL_RDMA_V1

we see test suite sends out SMB2_CHANNEL_RDMA_V1_INVALIDATE to which our server responds with "SMB_STATUS_NOT_SUPPORTED" as we do not support as of now.

However test case documentation for this case does not mention this. There are already cases which are specifically meant for invalidation in smb302 group.  

Since this is clearly SMB2_CHANNEL_RDMA_V1, it should not send SMB2_CHANNEL_RDMA_V1_INVALIDATE requests. So "SMB_STATUS_NOT_SUPPORTED" should be a considered as valid test result.

**Comment by huiren-jiang** [comment]
Hi vinitagnihotri,

Thanks for reporting this issue. 

You are right. `CHANNEL_RDMA_V1_INVALIDATE` should be changed to `CHANNEL_RDMA_V1` for write operation of test case `Smb2OverRdma_Read_SMB2_CHANNEL_RDMA_V1`. We will fix it later and notify you when it is committed to staging.
 
Best Regards,

Windows Protocol Test Suites Development Team

**Comment by huiren-jiang** [comment]
Hi vinitagnihotri,

The fix is available on staging by commit 8894ebd3a3d59a25e7fc02982d8177279c6c6400.

Here I attach a signed build with fix [MS-SMBD-TestSuite-ServerEP.msi.zip](https://github.com/microsoft/WindowsProtocolTestSuites/files/3914898/MS-SMBD-TestSuite-ServerEP.msi.zip). You could uninstall the old, then try this one to verify the fix.

Best Regards,

Windows Protocol Test Suites Development Team

**Comment by yazeng** [comment]
Hi vinitagnihotri,
Since this thread has been inactive for a long time, we close it for now. Feel free to reopen it if the problem remains.
Windows Protocol Test Suites Development Team
