### ISSUE TITLE
Mismatch between error message and documentation for test case ReplayCreateDurableHandleV2TestCaseS1067

### ISSUE THREAD

**Issue by harshivs** [microsoft/WindowsProtocolTestSuites#213]
We are observing a mismatch between documented flow of the said test case and the MS-SMB2 documentation.

Test error message reads:
```
3.3.5.9.10: If an Open is found and the SMB2_FLAGS_REPLAY_OPERATION bit is set in the SMB2 header, the server MUST verify the following: 
The server MUST fail the create request with STATUS_ACCESS_DENIED in the following cases: 
Open.IsDurable is FALSE
If Open.Lease is not NULL and Open.Lease.LeaseKey is not equal to the LeaseKey specified in the SMB2_CREATE_REQUEST_LEASE or SMB2_CREATE_REQUEST_LEASE_V2 Create Context
```

However as per the MS-SMB2 documentation for section 3.3.5.9.10, such checks does not seem to be mentioned.

Please find attached, snippets of the error message generated and of the relevant MS-SMB2 documentation.

![send1](https://user-images.githubusercontent.com/59079257/71235760-22080580-2323-11ea-812a-d8b489bb9ee7.png)
![send2](https://user-images.githubusercontent.com/59079257/71235766-246a5f80-2323-11ea-8b9b-c595ee045f9e.png)
![send3](https://user-images.githubusercontent.com/59079257/71235769-26ccb980-2323-11ea-8087-1f5b074b4c20.png)
![send4](https://user-images.githubusercontent.com/59079257/71236355-c63e7c00-2324-11ea-8ce4-94e579bdbecf.png)

**Comment by yazeng** [comment]
Hi Harshivs,

Thank you for reporting this issue. You’re right. The content is not in section 3.3.5.9.10. They are in section 3.3.5.9 actually. 

![Capture2](https://user-images.githubusercontent.com/10937464/71245142-0d416700-234f-11ea-9e8b-194ddc93cbc3.PNG)


So the server should fail the request with STATUS_ACCESS_DENIED, instead of STATUS_SUCCESS.
On the other hand, we will update the test cases to show the correct log.

Best Regards,
Yan 
Windows Protocol Test Suites Development Team

**Comment by harshivs** [comment]
thanks

**Comment by yazeng** [comment]
Hi Harshivs,
 
The log is updated in staging branch by the commit 1f810b2.
 
Best Regards,
Yan
Windows Protocol Test Suites Development Team

**Comment by yazeng** [comment]
Hi Harshivs,
Since this thread has been inactive for a long time, we close it for now. Feel free to reopen it if the problem remains.
Windows Protocol Test Suites Development Team
