### ISSUE TITLE
Is public void GetObjectFunctionality(out bool isImplemented) doing the right thing?

### ISSUE THREAD

**Issue by zherogerluo** [microsoft/WindowsProtocolTestSuites#214]
For SMB2 IOCTL tests, they call TestSuites/FileServer/src/FSA/Adapter/FSAAdapter.cs line 5205 to determine if certain FSCTL functionality is supported/implemented:
<pre>
public void GetObjectFunctionality(out bool isImplemented)
{
    isImplemented = (fileSystem == Adapter.FileSystem.FAT32) ? false : true;
}
</pre>
Is it really expected to output true for third party filesystems? I don't think it makes sense because these FSCTL ops are optional according to MS-FSA.

I propose to have an additional check for a property field in ptfconfig file (just like the old code before this commit) so that people can at lease customize it, something like this:
<pre>
public void GetObjectFunctionality(out bool isImplemented)
{
    isImplemented = (fileSystem == Adapter.FileSystem.FAT32) ? false : true;
    try {
        isImplemented = bool.Parse(testConfig.GetProperty("IsObjectFunctionality"));
    } catch {
        ...
    }
}
</pre>
Or mark all Microsoft filesystems that supports it to true instead of marking FAT32 as false:
<pre>
public void GetObjectFunctionality(out bool isImplemented)
{
    isImplemented = (fileSystem == Adapter.FileSystem.FS1_THAT_SHOULD_SUPPORT ||
                     fileSystem == Adapter.FileSystem.FS2_THAT_SHOULD_SUPPORT ||
                     ...) ? true : false;
}
</pre>

**Comment by yazeng** [comment]
Hi 

Thank you for reporting this issue. I agree with you. The function GetObjectFunctionality does not work properly. 
Since this function is called by 13 kinds of IOCTL test cases, It is not convenient to categorize those cases by file systems.
So my proposal to fix this is not to touch this function (GetObjectFunctionality), but to add a new ptfconfig property as below:
      <Property name="FSA_SupportedIoCtlCodes" value="FSCTL_DELETE_REPARSE_POINT;FSCTL_FIND_FILES_BY_SID;FSCTL_GET_REPARSE_POINT;FSCTL_SIS_COPYFILE"/>
For example, FSCTL_SET_ZERO_DATA is not shown in the property, which means it is not supported. 
Then the function FsCtlSetZeroData in FSAAdapter.cs should be modified to make case inconclusive.
Other FsCtl functions should be modified like FsCtlSetZeroData too.

We will fix this and notify you in this thread when the fix is pushed to staging branch if you have no other concerns.

Best Regards,
Yan
Windows Protocol Test Suites Development Team

**Comment by yazeng** [comment]
Hi Roger,

A new ptfconfig "FSCC_UnSupportedFSCTL" is added in commit ebbb0bd to classify the FSCTL cases in FSA test suite.
You can add the unsupported FSCTL code to it. (Different FSCTL code should be separated by “;”)
So that the test cases related to the unsupported FSCTL code will result in “Inconclusive”, instead of “Failed”.

Best Regards,
Yan
Windows Protocol Test Suites Development Team

**Comment by yazeng** [comment]
Hi Roger,
Since this thread has been inactive for a long time, we close it for now. Feel free to reopen it if the problem remains.
Windows Protocol Test Suites Development Team
