### ISSUE TITLE
Ptmcli.exe exits without any message

### ISSUE THREAD

**Issue by ligurio** [microsoft/WindowsProtocolTestSuites#216]
I want to execute tests without GUI tools and using [PtmCli.exe](https://github.com/Microsoft/WindowsProtocolTestSuites/wiki/PtmCli).

Tests runs fine with GUI Test Manager, but when I'm running them using PtmCli.exe it create junit.xml with zero size and exits. Is there any verbose mode in PtmCli?

Windows Protocol Test Framework 1.0.6000.0
Microsoft RDP Client Endpoint Test Suite 3.19.3.0
Protocol Test Manager 3.19.3.0
Windows 10

**Comment by JiajunW** [comment]
Hi Sergey,

Thanks for reporting this issue. Can you also tell us the full command you used for invoking PtmCli?

BTW, since version 3.19.9.0, PtmCli shows the progress in terminal, maybe it could meet your requirement as the verbose mode.

Best Regards,
Windows Protocol Test Suites Development Team

**Comment by ligurio** [comment]
Problem has gone, thanks!
