### ISSUE TITLE
[MS-RDPEGFX] invalid RDPGFX_CAPVERSION_106 value 

### ISSUE THREAD

**Issue by nfedera** [microsoft/WindowsProtocolTestSuites#226]
FreeRDP was failing basically all MS-RDPEGFX tests if xfreerdp was started with egfx support (e.g. `/gfx:avc444`) on the SUT.
In that case FreeRDP announces `RDPGFX_CAPVERSION_106` which is internally defined as `0x000A0601` according to  [2.2.1.6](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-rdpegfx/82e6dd00-914d-4dcc-bd17-985e1268ffb7).

The tests failed because of an alleged invalid cap version value `656897`, but that's the correct value  `0x000A0601` for  `RDPGFX_CAPVERSION_106`.

The issue was caused by an invalid define in the ProtoSDK which I fixed in PR https://github.com/microsoft/WindowsProtocolTestSuites/pull/225

**Comment by huiren-jiang** [comment]
Hi Norbert,
 
Thanks for your contribution. 
 
The tests failed because the value definition of `RDPGFX_CAPVERSION_106` is out of date in FreeRDP. The value given by [2.2.1.6]( https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-rdpegfx/82e6dd00-914d-4dcc-bd17-985e1268ffb7) is not the latest one. The actual value is `0x000A0600` and it could be found at [**errata**](https://winprotocoldoc.blob.core.windows.net/productionwindowsarchives/MS-RDPEGFX/%5bMS-RDPEGFX%5d-errata.pdf) of MS-RDPEGFX in 2018/12/10. The corresponding definition of ProtoSDK has been updated by commit 147a701 and your pull request might be unnecessary.
 
Best Regards,
 
Windows Protocol Test Suites Development Team

**Comment by nfedera** [comment]
@huiren-jiang allright, thanks for the info!
The fixes didn't make it in the current document since 2018?
I've checked the preview documents but missed the errata.
Sorry for the noise ;)
