### ISSUE TITLE
Visual Studio should not be a requirement

### ISSUE THREAD

**Issue by slupu-infinidat** [microsoft/WindowsProtocolTestSuites#232]
The Protocol Test Manager requires installing Visual Studio. As we understand, this is only required for the Visual Studio Console. This is seemingly an overkill. Shouldn't a simple console be sufficient?
While this is suitable for developers in Windows environment, it is inconvenient for developers who use Windows machines only for testing.

**Comment by yazeng** [comment]
Hi Lupu,

Thanks for your suggestion. We are currently exploring and investigating a new solution. With the new solution, Visual Studio may not be a required tool for our test suites.
We will let you know once we have any updates. 

Best Regards, 
Windows Protocol Test Suites Development Team

**Comment by slupu-infinidat** [comment]
We appreciate your response.

Shahar Lupu,
Infinidat

**Comment by yazeng** [comment]
Hi Shahar,

The latest released FileServer test suite v4.20.9.0 does not require installing Visual Studio.
The only prerequisites you need to install is [.NET Core 3.1 SDK](https://docs.microsoft.com/en-us/dotnet/core/install/).
Since this version of test suite is based on .NET Core, so that it can be run on not only Windows, but also Linux and macOS.
You can find details in the [release notes](https://github.com/microsoft/WindowsProtocolTestSuites/releases/tag/4.20.9.0).

Best Regards,
Windows Protocol Test Suite Team
****************************************
⭐⭐Join us at **SNIA SDC SMB IO Lab 2020 (9/21-9/23)**: https://interopevents.com/sniaonline2020

**Comment by hshavit-infinidat** [comment]
Thank you
