### ISSUE TITLE
Unable to run Lease2 test cases

### ISSUE THREAD

**Issue by vinitagnihotri** [microsoft/WindowsProtocolTestSuites#236]
Hi,
We are trying to run Lease2 tests against our windows 10 machine, however all test cases fails at same point.
Please find packet trace, MSFT profile file and test log output with attached zip file for a test case  "BreakReadWriteLeaseV2TestCaseS84".

We are using MSFT version: 3.20.1.0 

Test suite tried to open a  file with disposition info as 0x1 i.e. Open if exists or fail ( Pkt:1175), since this file does not exists
STATUS_OBJECT_NAME_NOT_FOUND is returned. After this test does not proceed and fails with 
"Expect that the Capabilities in the response does not contain SMB2_GLOBAL_CAP_LEASING".

Pkt: 1114,1154,1156 (negotaite response) clearly lists Leasing in capability

Are we missing any additional settings?

[leasev2_winsmb.zip](https://github.com/microsoft/WindowsProtocolTestSuites/files/5083213/leasev2_winsmb.zip)

**Comment by yazeng** [comment]
Hi vinitagnihotri,

The failure is caused by the incorrectly configured ptfconfig values: “IsLeasingSupported” and “IsDirectoryLeasingSupported”.
They should both be **true** if your server does support leasing and directory leasing.
Could you reconfigure the two values by PTM and have another try?

Best Regards,
Yan
Windows Protocol Test Suite Team
****************************************
⭐⭐Join us at **SNIA SDC SMB IO Lab 2020 (9/21-9/23)**: https://interopevents.com/sniaonline2020

**Comment by vinitagnihotri** [comment]
Yes, Thank you.
This solves our issue.
Closing issue as resolved.
