### ISSUE TITLE
BVT_SMB2Basic_Query_FileAllInformation file name length

### ISSUE THREAD

**Issue by gwr** [microsoft/WindowsProtocolTestSuites#240]
With our server, the Windows Protocol Test Suite fails this test case:
BVT_SMB2Basic_Query_FileAllInformation
 
The error reported is:
[CheckFailed] Assert Is True failed: FileNameLength in FileNameInformation should be set to 0, actually server returns 152.
 
What I see in this capture looks OK to me.  The file name length is set to the length (in bytes) of the file name.
Can anyone explain why this test seems to be expecting a zero there?
[wpts-qfi-all.zip](https://github.com/microsoft/WindowsProtocolTestSuites/files/5953159/wpts-qfi-all.zip)

**Comment by gwr** [comment]
OK, I see, at:  main/TestSuites/FileServer/src/SMB2/TestSuite/Basic/SMB2Basic.cs
starting at line 369, the comment says:
`            /*
             * If the information class is FileAllInformation,
             * the server SHOULD return an empty FileNameInformation
             * by setting FileNameLength field to zero and FileName field
             * to an empty string.
             */
`

Below this, there are tests for older servers returning the name.
Can anyone provide a reference to the MS-FSA spec. change for this?

Thanks!

**Comment by huiren-jiang** [comment]
Hi Gordon,
 
Actually the comment you attached refers to the below description in [MS-SMB2] section [3.3.5.20.1 Handling SMB2_0_INFO_FILE](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-smb2/d64e0451-64a2-425a-848e-52a7dddab7b9).
 
>If the information class is FileAllInformation, the server SHOULD<375> return an empty FileNameInformation by setting FileNameLength field to zero and FileName field to an empty string. If the store does not support the data requested, the server MUST fail the request with STATUS_NOT_SUPPORTED.
 
Best Regards,
 
Windows Protocol Test Suites Development Team

**Comment by gwr** [comment]
Ah, thanks for point that out.  So I guess that section "modifies" the behavior described in MS-FSA section 2.1.5.11.3 FileAllInformation.  It would help to have spec. references for tests like these, at least in the comments, but ideally in the error reports.  Looks like this is issue "not a bug" then and can be closed.  Thanks

**Comment by gwr** [comment]
One thing though: Given that the spec. says "should", maybe this test could issue a warning instead of an error.

**Comment by huiren-jiang** [comment]
Hi Gordon,

> Ah, thanks for point that out. So I guess that section "modifies" the behavior described in MS-FSA section 2.1.5.11.3 FileAllInformation. It would help to have spec. references for tests like these, at least in the comments, but ideally in the error reports. Looks like this issue is "not a bug" then and can be closed. Thanks

Your suggestion sounds good! We will improve the related code part so that user could easily find the corresponding part in technical specification.

> One thing though: Given that the spec. says "should", maybe this test could issue a warning instead of an error.

The usage of SHOULD often indicates that most Windows implementations conforms to the description except some specific versions given in appendix. For non-Windows implementation, the product behavior should conform to the description. Please refer to the below description of appendix.

> Unless otherwise specified, any statement of optional behavior in this specification that is prescribed using the terms "SHOULD" or "SHOULD NOT" implies product behavior in accordance with the SHOULD or SHOULD NOT prescription. Unless otherwise specified, the term "MAY" implies that the product does not follow the prescription.

Best Regards,
 
Windows Protocol Test Suites Development Team

**Comment by lumengyanhelen** [comment]
Hi Gordon,

Since this thread has been inactive for quite a long time, we will close it for now. Please feel free to reopen if the issue still exists.

Best Regards,
Windows Protocol Test Suites Development Team
---------------------------------------------

⭐⭐Join us at SambaXP SMB3 IO Lab 2021 (5/5-5/7): https://interopevents.com/sambaxp21
