### ISSUE TITLE
Auto-Detect issue when using IP 

### ISSUE THREAD

**Issue by liwass** [microsoft/WindowsProtocolTestSuites#246]
Hi, 

Trying version 4.21.5.0 against Windows Server 2016 and noticed that Auto-Detect using NTLM fails when IP is used, no issue for FQDN. 

[log.txt](https://github.com/microsoft/WindowsProtocolTestSuites/files/6661783/log.txt)

Thanks,
Lilia

**Comment by MaggieWang0** [comment]
Hi Lilia,

Thanks for your reporting this issue.

We are currently investigating on it. When there is update, we will notify you in this thread.

Best Regards,

Windows Protocol Test Suites Development Team

**Comment by Dingshouqing** [comment]
Hi Lilia,

I have checked the attached log and found that the failure seems to be caused by our NTLM implementation code issue, you can use FQDN or update SutComputerName to Ip Address and SupportedSecurityPacakge to NTLM on step “Configure Test Cases” if you still want use Ip and NTLM authentication to run your test.

We will work on the fix and include it in our later releases.
Let me know if you have more questions 😊. 

Thanks.
 
Best Regards,
Windows Protocol Test Suites Development Team
