### ISSUE TITLE
WindowsProtocolTestSuites : STATUS_LOGON_FAILURE

### ISSUE THREAD

**Issue by shloro** [microsoft/WindowsProtocolTestSuites#247]
Hi,
I'm trying to test WindowsProtocolTestSuites over SMB server, we support in SMB2.1.
I've configured manual profile over Domain environment, and tried both NTLM and Kerberos setup.
In most of the tests, I get errors (UI or CLI)..
For NTLM:
`System.ArgumentNullException: Value cannot be null. (Parameter 'targetName')`

while in Kerberos:
`Expected KerberosAsResponse data is null`

Any idea what I'm doing wrong?

**Comment by Dingshouqing** [comment]
Hi shloro,

Thanks for contacting us, Could you provide a network capture for both NTLM and Kerberos to us for further investigation?

From the exception log it seems caused by your driver machine cannot resolve the Ip address by SMB server name or Domain name, you can try if you could ping your SUT and domain by machine name or NetBios name.

We did a bug fix for both NTLM and Kerberos recently, so you can try if the issue still exists after using our latest code.
you can find how to build our TestSuite code from our Github portal https://github.com/microsoft/WindowsProtocolTestSuites

Best Regards,
Windows Protocol Test Suites Development Team

**Comment by shloro** [comment]
Hi, 
So I did some fixes on DNS record side. 
Now I get error `STATUS_LOGON_FAILURE`, due to GSS error (frame #306, 13:18:26.273892).
TCP Dump attached.

* ignore dialect SMB 2.02 errors, we currently support only SMB2.1.
[vast_proto_test_suite_logon_failure_mykola.pcapng.zip](https://github.com/microsoft/WindowsProtocolTestSuites/files/7026708/vast_proto_test_suite_logon_failure_mykola.pcapng.zip)

**Comment by Dingshouqing** [comment]
Hi shloro,

Thanks for sending the network capture!

“STATUS_LOGON_FAILURE” may be caused by a different reason. Could you help try below:
1.	Please check if the time difference between client, server, and domain (>5 minutes)
2.	Try if NTLM SSP can work, if not could you send us the network capture?
3.	I have attached a private build that will use windows native SSP to do authentication, please also have a try and send us the network capture whether it can work or not.

Could you also give us more details about your test environment? Such as OS type, version, network structure.
We may need your test credential to parse some of the content in Kerberos token from the capture file, However, Let’s try with the above steps first.

[FileServerPrivateBuild](https://vicding-my.sharepoint.com/:u:/g/personal/victor_vicding_onmicrosoft_com/EbqFtl2C9pRAh1i6__YBWWwBodzQLbtdRHAK5m4cMcsA8g?e=OlitFR)

Best Regards,
Windows Protocol Test Suites Development Team

**Comment by lumengyanhelen** [comment]
Since this thread has been inactive for a long time, we will close for now. Feel free to reactivate the issue if you still have any questions.

Best Regards,
Windows Protocol Test Suites Development Team
