### ISSUE TITLE
play list support, or method to re-run single tests

### ISSUE THREAD

**Issue by gwr** [microsoft/WindowsProtocolTestSuites#253]
The old ProtocolTestManager U/I had a "play list" feature, where you could save a list of tests
(after running the tool that selects which tests to run).
One could then edit that play list to run a subset, or even just one test.

I'd like a way to do that with the current Protocol Test Manager CLI,
but I don't see any such features.  Is there one?  If not, this is a feature request.

Thanks

**Comment by Dingshouqing** [comment]
Hi Gordon,

Thanks for contacting us.

Current Protocol Test Manager CLI does not support the “play list” feature, we’ll add this requirement to our backlog.

The old ProtocolTestManager GUI is deprecated as for not supporting cross-platform, you could try our new PTMService which supports running on different more platforms like Windows, Linux, and macOS.
The new PTMService is similar to the old GUI tool and supports “play list”, you could select cases you want to run and also support check history run result, you could have a try.
For more details please visit our wiki page: [PTMService](https://github.com/microsoft/WindowsProtocolTestSuites/wiki/PTMService)
![ptmservice](https://user-images.githubusercontent.com/17266569/148724958-d504701e-2d3c-4500-ba3b-fd3af8920e04.png)


Best Regards,
Windows Protocol Test Suites Development Team

**Comment by gwr** [comment]
Thanks very much.  I have not looked at the PTMService yet.
Does that offer a way to re-run a single test?

**Comment by Dingshouqing** [comment]
Hi Gordon,

Yes, PTMService can re-run a single test!

- #Option 1
  Click the “Run” button of the previously created configuration
  ![1](https://user-images.githubusercontent.com/17266569/148872892-f8469fa3-7e39-4271-bca5-077a8663aeee.png)
  Select test you want to run/re-run then click “Run selected cases”
![2](https://user-images.githubusercontent.com/17266569/148873004-05c2f71d-6dee-4fc5-b72b-b4dcd5620306.png)
  After clicking the “Run selected cases” button it will auto navigate to the “View History” page, you could click “go back”  and then will go back to the “Run Selected Test Case” page and you could select a case to run/re-run again
![3](https://user-images.githubusercontent.com/17266569/148873097-5f50d315-9094-4366-841f-9e419b5471f2.png)

- #Option 2
  Click the “View History” link on top and then find the previous run record and click “View Result”
![4](https://user-images.githubusercontent.com/17266569/148873202-cbdd90ec-38a7-4c16-8e0b-b08a1beaf33e.png)
  Select test you want to re-run and then click “Rerun Selected Cases”
![5](https://user-images.githubusercontent.com/17266569/148873229-86438080-6930-4c85-9c22-b16760aa301a.png)

Best Regards,
Windows Protocol Test Suites Development Team

**Comment by gwr** [comment]
It would be handy to be able to specify a playlist (or single test name) for the PTM CLI.
However, the PTM service is a useful work-around for that deficiency of the CLI.
Thanks.

**Comment by Dingshouqing** [comment]
Hi Gordon,

PTMCli supports users to specify a filter expression to run selected tests, this could help you to be able to run specific tests by name or category instead of providing a playlist.
For example:
Run tests which name contains “CreateFileTestCasesS20”
```
PTMCli.exe -p fileserver.ptm -t "C:\FileServer-TestSuite-ServerEP" --filter "Name~CreateFileTestCaseS20"
```
Run Tests which category equals to “CreateFile”
```
PTMCli.exe -p fileserver.ptm -t "C:\FileServer-TestSuite-ServerEP" --filter "TestCategory=CreateFile"
```

You could download our [latest released PTMCli](https://github.com/microsoft/WindowsProtocolTestSuites/releases/tag/4.21.9.0) to have a try.
We’ll update our PTMCli wiki page accordingly.

For more details about how to use --filter please refer to this document: [Run selected unit tests - .NET | Microsoft Docs](https://docs.microsoft.com/en-us/dotnet/core/testing/selective-unit-tests?pivots=mstest)

Best Regards,
Windows Protocol Test Suites Development Team

**Comment by lumengyanhelen** [comment]
Hi Gordon,

Since this thread has been inactive for some time, we will close it for now. Please feel free to contact us if there is any further question.

Best Regards,
Windows Protocol Test Suites Development Team
-------------------------------------------------------
⭐⭐Join us at SNIA EMEA SDC SMB3 IO Lab 2022 (4/5-4/7): 
https://interopevents.com/en-us/snia2022
