### ISSUE TITLE
RSVDv1 test - ReconnectSharedVHDWithoutDeviceContext  failing

### ISSUE THREAD

**Issue by ahmedha** [Microsoft/WindowsProtocolTestSuites#62]
Hello,

I am running the RSVD Version 1 tests against our RSVDv1 implementation.  Most of the tests are passing, however the following test is failing:
      ReconnectSharedVHDWithoutDeviceContext

In my setup, I have the following setting:
SupportedSecurityPackage = Ntlm   (To avoid using Kerberos)
IsRequiredMessageSigning = false   (To disable signing of packets)

I am attaching a network wire trace, which shows the test stopped performing a "Session Setup", and performed a "Tree Disconnect".

[ReconnectSharedVHDWithoutDeviceContext_FAIL.pcapng.zip](https://github.com/Microsoft/WindowsProtocolTestSuites/files/338058/ReconnectSharedVHDWithoutDeviceContext_FAIL.pcapng.zip)

Can you please tell me what other test logs you need from the test run, and from which location (on the test client) I can get them.

Thank you,
Ahmed.

**Comment by yazeng** [comment]
Hi Ahmed,
Yes, I need the test suite log.
If you use PTM to run the test suite, you should be able to find the logs in this path: C:\MicrosoftProtocolTests\FileServer\Server-Endpoint\1.0.5000.0\HtmlTestResults\
Each test run has its own folder, and in each folder, there is an "txt" folder which contains the txt format logs. 
So could you send me the .txt file of this case?

Thanks,
Yan

**Comment by ahmedha** [comment]
Hello Yan,

Thank you for looking into the issue.  Please find attached the "txt" log file.  Please let me know if you need any additional info.

[2016-06-28-12-56-25_Failed_ReconnectSharedVHDWithoutDeviceContext.txt](https://github.com/Microsoft/WindowsProtocolTestSuites/files/339872/2016-06-28-12-56-25_Failed_ReconnectSharedVHDWithoutDeviceContext.txt)

Thank you,
Ahmed.

**Comment by yazeng** [comment]
Hi Ahmed,
The failure is caused by timeout. The test case will try to get service principal name of your server. It may take time if your server does not have a DNS entry in Domain Controller. You can see in the trace, the test case took 7 seconds between receiving Negotiate response and sending Session setup request. So the simple solution to your issue is to enlarge the timeout value.
![timeout](https://cloud.githubusercontent.com/assets/10937464/16510119/f8983290-3f75-11e6-95a5-12bfb14945e2.png)

And we will fix this issue in test suite too. (Do not query DNS if only Server IP address is given.)

Btw, the "Tree Disconnect" was not sent by test case, should be sent by real Windows client.
Let me know how it works.
Thanks,
Yan

**Comment by yazeng** [comment]
Hi Ahmed,
The issue is fixed: Do not query DNS if only Server IP address is given.
Could you try again by using the latest code to build a new PTM?

Thanks,
Yan

**Comment by yazeng** [comment]
Close it since no response for a long time.
