### ISSUE TITLE
ResilientHandleDurable Tests

### ISSUE THREAD

**Issue by eliadCohenVs** [Microsoft/WindowsProtocolTestSuites#83]
Hi,
 
I've got several tests that i don't understand why thy are failing.
ResilientHandleDurableTestCaseS725
ResilientHandleDurableTestCaseS948
ResilientHandleDurableTestCaseS996
ResilientHandleDurableTestCaseS1625
ResilientHandleDurableTestCaseS1694
ResilientHandleDurableTestCaseS1768
ResilientHandleDurableTestCaseS1793
ResilientHandleDurableTestCaseS1227
ResilientHandleDurableTestCaseS1148
 
The scenario sequence:
create(durable)
resilient
RST
create(reconnect)
 
The test expect to fail with "STATUS_OBJECT_NOT_FOUND" and our server return "SUCCESS"
 
Can you explain why the test suppose to fail?

Best Regards,
Eliad Cohen
Visuality Systems Ltd.

**Comment by chenlu0616** [comment]
Hi, Eliad

These test cases are generated by model, which are designed to test whether server can correctly handle the situation that the client uses a different user to reconnect to the server. The scenario sequence is like the following:
1. create(durable)
2. resilient
3. disconnect
4. create(reconnect with a different user)

This scenario is to test cover the MS-SMB2 section 3.3.5.9.7: If the user represented by Session.SecurityContext is not the same user denoted by Open.DurableOwner, the server MUST fail the request with STATUS_ACCESS_DENIED and proceed as specified in "Failed Open Handling" in section 3.3.5.9. Thus, the test expect to fail with "STATUS_ACCESS_DENIED" instead of "STATUS_OBJECT_NOT_FOUND".

In addition, if you want a detailed explanation, I need to look into the test logs generated by the test cases in your execution. If you use PTM to run the test suite, you should be able to find the logs in this path: C:\MicrosoftProtocolTests\FileServer\Server-Endpoint\1.0.5000.0\HtmlTestResults\
Each test run has its own folder, and in each folder, there is an "txt" folder which contains the txt format logs. 

Thanks,
Lu

**Comment by eliadCohenVs** [comment]
Thanks for the response.

I'm attaching a zip file with a *.pcap file and you log.
The test is ResilientHandleDurableTestCaseS1148.
It seem that the user is the same one.

*Best Regards,*
*Eliad Cohen*
*Visuality Systems Ltd.*
*www.visualitynq.com* <http://www.visualitynq.com/>
*Tel:        +972 4 959 2155 <%2B972%204%20959%202155>*
*Fax:       +972 4 959 2173 <%2B972%204%20959%202173>*
*Mobile : +972 524 433 813*

**Comment by chenlu0616** [comment]
Hi, Eliad

I cannot see your zip file through github or received email, could you upload it through this site? 
https://github.com/Microsoft/WindowsProtocolTestSuites/issues/83 

In addition, the different user needs to be configured in the confilg file named "CommonTestSuite.deployment.ptfconfig", in our test case, the first create(durable) uses the "Administrator" user, and the reconnect with a different user will use "nonadmin", make sure they are different:
![image](https://cloud.githubusercontent.com/assets/18330323/17395658/32b70a76-5a62-11e6-80b5-5db0ff374eaf.png)

Thanks,
Lu

**Comment by eliadCohenVs** [comment]
Hi Lu,

Here is the zip file

[ResilientHandleDurableTestCaseS1148.zip](https://github.com/Microsoft/WindowsProtocolTestSuites/files/401224/ResilientHandleDurableTestCaseS1148.zip)

Thanks 
Eliad

**Comment by chenlu0616** [comment]
Hi, Eliad

I looked into the test log and found that the test case failed because leasing is not support. 

During create reconnect, as MS-SMB2 describes in section 3.3.5.9.7: The server MUST look up an existing open in the GlobalOpenTable by doing a lookup with the FileId.Persistent portion of the create context. If the lookup fails, the server SHOULD<268> fail the request with STATUS_OBJECT_NAME_NOT_FOUND and proceed as specified in "Failed Open Handling" in section 3.3.5.9."

The test case ResilientHandleDurableTestCaseS1148 considered it failed to lookup because according to MS-SMB2, the open is not preserved after Disconnect if the leasing is not support. As described in section 3.3.7.1： §	The server MUST iterate over the Session.OpenTable and determine whether each Open is to be preserved for reconnect. If any of the following conditions is satisfied, it indicates that the Open is to be preserved for reconnect. 
§	The server supports leasing and Open.IsResilient is TRUE.
...
Since the leasing is not support, the test considers the Open will not be preserved for reconnect, thus it expects fail with "STATUS_OBJECT_NAME_NOT_FOUND", while actually the server returns "STATUS_SUCCESS".

However, it seems that the "The server supports leasing" is not a required condition for server to preserve the open. We have removed the check for Leasing support in resilient related test cases in the latest code, you can sync the latest code to have a try, let me know if this does work for you.


Thanks,
Lu

**Comment by eliadCohenVs** [comment]
Hi Lu,

Sorry for the late response,
The change is working :)

Thanks again
