### ISSUE TITLE
WiX build failure

### ISSUE THREAD

**Issue by KipRepscher** [Microsoft/WindowsProtocolTestSuites#92]
Hitting this same build failure with this project:
https://github.com/Microsoft/ProtocolTestFramework/issues/18

Tried loading the 'msi' files from the most recent published Release, but it seems out of date (Build 1.0.5000 from May 26).
Installed the ProtocolTestManager.msi, MS-SMB-Testsuite-ServerEP.msi, and FileServer-TestSuite-ServerEP.msi

After installing the Protocol Test Manager I get an error in the Select Test Suite of the Wizard:

![errormessage](https://cloud.githubusercontent.com/assets/22969625/19787468/c81fb482-9c57-11e6-9cbb-fe44bf579c03.PNG)

**Comment by yazeng** [comment]
Hi Kip,
1.0.5000.0 is the latest PTF. It has not been updated for a while.
What PTF did you install? Is it ProtocolTestFrameworkInstallerForModel.msi?
If you installed ProtocolTestFrameworkInstaller.msi, you need to uninstall it and reinstall ProtocolTestFrameworkInstallerForModel.msi
File Server test suite has model-based test cases, that's why it needs the PTF with "ForModel" suffix.

And did you build FileServer-TestSuite-ServerEP.msi by yourself or you download it here:
https://github.com/Microsoft/WindowsProtocolTestSuites/releases
If you build it by yourself, you need to rebuild it again after you install the correct PTF. And then reinstall the test suite again.
If you download it from our release site, then you should be able to use it if you install the correct PTF.

Thanks,
Yan

**Comment by KipRepscher** [comment]
I installed the 1.0.5000 "ForModel" PTF, msi downloaded from the GitHub releases link.

Does the error I linked correlate with having a PTF with no "ForModel" installed?

**Comment by KipRepscher** [comment]
Okay, I uninstalled all of the components and reinstalled them.

When doing this the first time I installed the components in the following order:
PTF
TestSuites
PTM

This time I installed them using the same installation files:
PTF
PTM
TestSuites

It appears to be working now.  SUT discovery worked, it has started the first test run.

**Comment by yazeng** [comment]
Close it since it's working now.
