### ISSUE TITLE
test case "CreditMgmtTestCaseS776" payload does not equal to the current payload

### ISSUE THREAD

**Issue by eliadCohenVs** [Microsoft/WindowsProtocolTestSuites#98]
I have the test capture and the log file is not match to what is written in the file log error.(the test fails)

The log file has the following text:
2017-01-16 16:45:18.450 [Debug] *****customizedMId = 5

2017-01-16 16:45:18.451 [Debug] *****customizedCreditCharge = 2

2017-01-16 16:45:18.451 [Debug] *****customizedCreditRequest = 0

But i can't see this info in the capture.

I am attaching the logs and the file capture.
[Out_16_1_17_CreditMgmtTestCaseS776.zip](https://github.com/Microsoft/WindowsProtocolTestSuites/files/708703/Out_16_1_17_CreditMgmtTestCaseS776.zip)

**Comment by yazeng** [comment]
Hi Eliad,

Do you mean you cannot see the Write Request?
Actually, Write Request was sent by client,
see the frame 156:

![snip_20170117164641](https://cloud.githubusercontent.com/assets/10937464/22013574/adfe51d6-dcd4-11e6-92d8-24c6cd1d1029.png)

It is the first tcp packet of Write.
Write Request is fragmented in TCP layer.
But something wrong happened in TCP, so that the packet cannot be reassembled to be a Write Request.
![snip_20170117164922](https://cloud.githubusercontent.com/assets/10937464/22013632/fcb4c198-dcd4-11e6-9166-dca52ea72a79.png)

I also attached my capture.
[CreditMgmtTestCaseS776.zip](https://github.com/Microsoft/WindowsProtocolTestSuites/files/710433/CreditMgmtTestCaseS776.zip)

Hope that helps.
Thanks,
Yan

**Comment by eliadCohenVs** [comment]
Thanks that helps.
